---
swagger: "2.0"
info:
  description: "This is a sample for swagger-maven-plugin"
  version: "v1"
  title: "Swagger Maven Plugin Sample"
  termsOfService: "http://localhost:8080"
  contact:
    name: "Denis Volnenko"
    url: "http://www.volnenko.ru"
    email: "denis@volnenko.ru"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080/api"
tags:
- name: "Дата"
- name: "Задача"
- name: "Проект"
schemes:
- "http"
- "https"
paths:
  /api/v1/datetime/current:
    get:
      tags:
      - "Дата"
      summary: "Получение текущей даты"
      description: ""
      operationId: "date"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/DateDTO"
  /api/v1/project/all:
    get:
      tags:
      - "Проект"
      summary: "Получение всех проектов"
      description: ""
      operationId: "selectAllProject"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ProjectDTO"
    post:
      tags:
      - "Проект"
      summary: "Создание новых проектов"
      description: ""
      operationId: "createAllProject"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          type: "array"
          items:
            $ref: "#/definitions/ProjectDTO"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ResultRecord"
  /api/v1/project/one/{id}:
    get:
      tags:
      - "Проект"
      summary: "Получение проекта по Id"
      description: ""
      operationId: "selectOneProject"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Идентификатор"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ProjectDTO"
    post:
      tags:
      - "Проект"
      summary: "Создание нового проекта"
      description: ""
      operationId: "createOneProject"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Идентификатор"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/ProjectDTO"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ResultRecord"
  /api/v1/task/all:
    get:
      tags:
      - "Задача"
      summary: "Получение всех задач"
      description: ""
      operationId: "selectAllTask"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TaskDTO"
    post:
      tags:
      - "Задача"
      summary: "Создание новых задач"
      description: ""
      operationId: "createAllTask"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          type: "array"
          items:
            $ref: "#/definitions/TaskDTO"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ResultRecord"
  /api/v1/task/one/{id}:
    get:
      tags:
      - "Задача"
      summary: "Получение задачи по Id"
      description: ""
      operationId: "selectOneTask"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Идентификатор"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/TaskDTO"
    post:
      tags:
      - "Задача"
      summary: "Создание новой задачи"
      description: ""
      operationId: "createOneTask"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Идентификатор"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/TaskDTO"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ResultRecord"
securityDefinitions:
  basicAuth:
    type: "basic"
definitions:
  DateDTO:
    type: "object"
    properties:
      date:
        type: "string"
        format: "date-time"
        description: "Дата/Время"
    description: "Класс для передачи даты и времени"
  ProjectDTO:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Название"
      description:
        type: "string"
        description: "Описание"
      version:
        type: "integer"
        format: "int32"
        description: "Версия"
      created:
        type: "string"
        format: "date-time"
        description: "Дата создания"
      updated:
        type: "string"
        format: "date-time"
        description: "Дата обновления"
    description: "Проект"
  ResultRecord:
    type: "object"
    properties:
      success:
        type: "boolean"
        description: "Флаг успешного выполнения"
    description: "Результат выполнения"
  TaskDTO:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Название"
      description:
        type: "string"
        description: "Описание"
      version:
        type: "integer"
        format: "int32"
        description: "Версия"
      created:
        type: "string"
        format: "date-time"
        description: "Дата создания"
      updated:
        type: "string"
        format: "date-time"
        description: "Дата обновления"
    description: "Задача"
