components:
  schemas:
    Project:
      type: object
      description: Проект
      properties:
        id:
          type: string
          format: uuid
          description: Идентификатор
        name:
          type: string
          description: Название
        created:
          type: string
          format: iso8601
          description: Дата создания
        updated:
          type: string
          format: iso8601
          description: Дата создания
