components:
  schemas:
    Project:
      type: object
      description: Проект
      properties:
        id:
          type: string
          format: uuid
          description: Идентификатор
        name:
          type: string
          description: Название
